export const providers = [
  {
    key: "1",
    id: "1",
    title: "CLINICA GOMEZ PATI\u00d1O",
    name: "CLINICA GOMEZ PATI\u00d1O",
    city: "Distrito Nacional",
    citySelect: "Distrito Nacional",
    type: "Cl\u00ednica",
    typeSelect: "Laboratorio",
    phone: "809.685.9131",
    phoneText: "809.685.9131",
  },
  {
    key: "2",
    id: "2",
    title: "LABORATORIO CLINICO ASOCIADO",
    name: "LABORATORIO CLINICO ASOCIADO",
    city: "Distrito Nacional",
    citySelect: "Distrito Nacional",
    type: "Laboratorio",
    typeSelect: "Laboratorio",
    phone: "809.688.5086",
    phoneText: "809.688.5086",
  },
  {
    key: "3",
    id: "3",
    title: "FARMACIA ADA",
    name: "FARMACIA ADA",
    city: "Distrito Nacional",
    citySelect: "Distrito Nacional",
    type: "M\u00e9dico",
    typeSelect: "M\u00e9dico",
    phone: "809.684.1588",
    phoneText: "809.684.1588",
  },
  {
    key: "4",
    id: "4",
    title: "ADA CENTRO DIAGNOSTICO, SRL",
    name: "ADA CENTRO DIAGNOSTICO, SRL",
    city: "Distrito Nacional",
    citySelect: "Distrito Nacional",
    type: "Cl\u00ednica",
    typeSelect: "Cl\u00ednica",
    phone: "809.621.2122",
    phoneText: "809.621.2122",
  },
  {
    key: "7",
    id: "7",
    title: "AMADITA ARROYO HONDO",
    name: "AMADITA ARROYO HONDO",
    city: "Distrito Nacional",
    citySelect: "Distrito Nacional",
    type: "Laboratorio",
    typeSelect: "Laboratorio",
    phone: "809.621.5414",
    phoneText: "809.621.5414",
  },
  {
    key: "9",
    id: "9",
    title: "AMADITA BELLA VISTA",
    name: "AMADITA BELLA VISTA",
    city: "Distrito Nacional",
    citySelect: "Distrito Nacional",
    type: "Laboratorio",
    typeSelect: "Laboratorio",
    phone: "809.621.5414",
    phoneText: "809.621.5414",
  },
  {
    key: "11",
    id: "11",
    title: "AMADITA CRESA",
    name: "AMADITA CRESA",
    city: "Distrito Nacional",
    citySelect: "Distrito Nacional",
    type: "Laboratorio",
    typeSelect: "Laboratorio",
    phone: "809.621.5414",
    phoneText: "809.621.5414",
  },
  {
    key: "13",
    id: "13",
    title: "AMADITA INDEPENDENCIA",
    name: "AMADITA INDEPENDENCIA",
    city: "Distrito Nacional",
    citySelect: "Distrito Nacional",
    type: "Laboratorio",
    typeSelect: "Laboratorio",
    phone: "809.621.5414",
    phoneText: "809.621.5414",
  },
  {
    key: "15",
    id: "15",
    title: "AMADITA LA ESPERILLA",
    name: "AMADITA LA ESPERILLA",
    city: "Distrito Nacional",
    citySelect: "Distrito Nacional",
    type: "Laboratorio",
    typeSelect: "Laboratorio",
    phone: "809.621.5414",
    phoneText: "809.621.5414",
  },
  {
    key: "17",
    id: "17",
    title: "AMADITA MARIA AUXILIADORA",
    name: "AMADITA MARIA AUXILIADORA",
    city: "Distrito Nacional",
    citySelect: "Distrito Nacional",
    type: "Laboratorio",
    typeSelect: "Laboratorio",
    phone: "809.621.5414",
    phoneText: "809.621.5414",
  },
  {
    key: "20",
    id: "20",
    title: "AMADITA NACO",
    name: "AMADITA NACO",
    city: "Distrito Nacional",
    citySelect: "Distrito Nacional",
    type: "Laboratorio",
    typeSelect: "Laboratorio",
    phone: "809.621.5414",
    phoneText: "809.621.5414",
  },
  {
    key: "22",
    id: "22",
    title: "AMADITA PIANTINI",
    name: "AMADITA PIANTINI",
    city: "Distrito Nacional",
    citySelect: "Distrito Nacional",
    type: "Laboratorio",
    typeSelect: "Laboratorio",
    phone: "809.621.5414",
    phoneText: "809.621.5414",
  },
  {
    key: "23",
    id: "23",
    title: "AMADITA PRENATAL CARE",
    name: "AMADITA PRENATAL CARE",
    city: "Distrito Nacional",
    citySelect: "Distrito Nacional",
    type: "Laboratorio",
    typeSelect: "Laboratorio",
    phone: "809.621.5414",
    phoneText: "809.621.5414",
  },
  {
    key: "30",
    id: "30",
    title: "ASOCIACION DOMINICANA DE REHABILITACION",
    name: "ASOCIACION DOMINICANA DE REHABILITACION",
    city: "Distrito Nacional",
    citySelect: "Distrito Nacional",
    type: "Cl\u00ednica",
    typeSelect: "Cl\u00ednica",
    phone: "809.689.7151",
    phoneText: "809.689.7151",
  },
  {
    key: "31",
    id: "31",
    title: "ASOCIACION INSTITUTO DOMINICANO DE CARDIOLOGIA",
    name: "ASOCIACION INSTITUTO DOMINICANO DE CARDIOLOGIA",
    city: "Distrito Nacional",
    citySelect: "Distrito Nacional",
    type: "Cl\u00ednica",
    typeSelect: "Cl\u00ednica",
    phone: "809.566.2219",
    phoneText: "809.566.2219",
  },
  {
    key: "33",
    id: "33",
    title: "BANCO DE SANGRE I D C, SRL",
    name: "BANCO DE SANGRE I D C, SRL",
    city: "Distrito Nacional",
    citySelect: "Distrito Nacional",
    type: "Laboratorio",
    typeSelect: "Laboratorio",
    phone: "809.683.1939",
    phoneText: "809.683.1939",
  },
  {
    key: "34",
    id: "34",
    title: "BRACA",
    name: "BRACA",
    city: "Distrito Nacional",
    citySelect: "Distrito Nacional",
    type: "Cl\u00ednica",
    typeSelect: "Cl\u00ednica",
    phone: "809.683.6564",
    phoneText: "809.683.6564",
  },
  {
    key: "36",
    id: "36",
    title: "CARIMED SERVICES, INC",
    name: "CARIMED SERVICES, INC",
    city: "Distrito Nacional",
    citySelect: "Distrito Nacional",
    type: "Cl\u00ednica",
    typeSelect: "Cl\u00ednica",
    phone: "(829).544.51",
    phoneText: "(829).544.51",
  },
  {
    key: "38",
    id: "38",
    title: "CDD RADIOTERAPIA, SRL",
    name: "CDD RADIOTERAPIA, SRL",
    city: "Distrito Nacional",
    citySelect: "Distrito Nacional",
    type: "Cl\u00ednica",
    typeSelect: "Cl\u00ednica",
    phone: "809.221.1999",
    phoneText: "809.221.1999",
  },
  {
    key: "40",
    id: "40",
    title: "CEDIMAT",
    name: "CEDIMAT",
    city: "Distrito Nacional",
    citySelect: "Distrito Nacional",
    type: "Cl\u00ednica",
    typeSelect: "Cl\u00ednica",
    phone: "809.565.9989",
    phoneText: "809.565.9989",
  },
  {
    key: "41",
    id: "41",
    title: "CEIMBIOCIT",
    name: "CEIMBIOCIT",
    city: "Distrito Nacional",
    citySelect: "Distrito Nacional",
    type: "Cl\u00ednica",
    typeSelect: "Cl\u00ednica",
    phone: "809.732.2299",
    phoneText: "809.732.2299",
  },
  {
    key: "42",
    id: "42",
    title: "CEMADOJA",
    name: "CEMADOJA",
    city: "Distrito Nacional",
    citySelect: "Distrito Nacional",
    type: "Cl\u00ednica",
    typeSelect: "Cl\u00ednica",
    phone: "809.684.0411",
    phoneText: "809.684.0411",
  },
  {
    key: "44",
    id: "44",
    title: "CENTRO CARDIOVASCULAR DOMINICANO",
    name: "CENTRO CARDIOVASCULAR DOMINICANO",
    city: "Distrito Nacional",
    citySelect: "Distrito Nacional",
    type: "Cl\u00ednica",
    typeSelect: "Cl\u00ednica",
    phone: "809.689.6785",
    phoneText: "809.689.6785",
  },
  {
    key: "55",
    id: "55",
    title: "CENTRO DE GASTROENTEROLOGIA",
    name: "CENTRO DE GASTROENTEROLOGIA",
    city: "Distrito Nacional",
    citySelect: "Distrito Nacional",
    type: "Cl\u00ednica",
    typeSelect: "Cl\u00ednica",
    phone: "809.684.1095",
    phoneText: "809.684.1095",
  },
  {
    key: "61",
    id: "61",
    title: "CENTRO DE MEDICINA FISICA Y REHABILITACION",
    name: "CENTRO DE MEDICINA FISICA Y REHABILITACION",
    city: "Distrito Nacional",
    citySelect: "Distrito Nacional",
    type: "Cl\u00ednica",
    typeSelect: "Cl\u00ednica",
    phone: "809.682.1481",
    phoneText: "809.682.1481",
  },
  {
    key: "64",
    id: "64",
    title: "CENTRO DE RADIOLOGIA INTEGRAL (RADONIC)",
    name: "CENTRO DE RADIOLOGIA INTEGRAL (RADONIC)",
    city: "Distrito Nacional",
    citySelect: "Distrito Nacional",
    type: "Cl\u00ednica",
    typeSelect: "Cl\u00ednica",
    phone: "809.534.2170",
    phoneText: "809.534.2170",
  },
  {
    key: "65",
    id: "65",
    title: "CENTRO DE REHABILITACION FUNCIONAL ERGO",
    name: "CENTRO DE REHABILITACION FUNCIONAL ERGO",
    city: "Distrito Nacional",
    citySelect: "Distrito Nacional",
    type: "Cl\u00ednica",
    typeSelect: "Cl\u00ednica",
    phone: "809.530.4080",
    phoneText: "809.530.4080",
  },
  {
    key: "66",
    id: "66",
    title: "CENTRO DE REHABILITACION GAZCUE",
    name: "CENTRO DE REHABILITACION GAZCUE",
    city: "Distrito Nacional",
    citySelect: "Distrito Nacional",
    type: "Cl\u00ednica",
    typeSelect: "Cl\u00ednica",
    phone: "809.682.2747",
    phoneText: "809.682.2747",
  },
  {
    key: "72",
    id: "72",
    title: "CENTRO DIAGNOSTICO RIA",
    name: "CENTRO DIAGNOSTICO RIA",
    city: "Distrito Nacional",
    citySelect: "Distrito Nacional",
    type: "Cl\u00ednica",
    typeSelect: "Cl\u00ednica",
    phone: "809.616.0506",
    phoneText: "809.616.0506",
  },
  {
    key: "74",
    id: "74",
    title: "CENTRO DIAGNOSTICOS Y ESPECIALIDADES (CEDISA)",
    name: "CENTRO DIAGNOSTICOS Y ESPECIALIDADES (CEDISA)",
    city: "Distrito Nacional",
    citySelect: "Distrito Nacional",
    type: "Cl\u00ednica",
    typeSelect: "Cl\u00ednica",
    phone: "809.687.1103",
    phoneText: "809.687.1103",
  },
  {
    key: "77",
    id: "77",
    title: "CENTRO MEDICO ALC?NTARA & GONZ?LEZ",
    name: "CENTRO MEDICO ALC?NTARA & GONZ?LEZ",
    city: "Distrito Nacional",
    citySelect: "Distrito Nacional",
    type: "Cl\u00ednica",
    typeSelect: "Cl\u00ednica",
    phone: "809.566.2121",
    phoneText: "809.566.2121",
  },
  {
    key: "93",
    id: "93",
    title: "CENTRO MEDICO DR. BORBON",
    name: "CENTRO MEDICO DR. BORBON",
    city: "Distrito Nacional",
    citySelect: "Distrito Nacional",
    type: "Cl\u00ednica",
    typeSelect: "Cl\u00ednica",
    phone: "809.333.7232",
    phoneText: "809.333.7232",
  },
  {
    key: "110",
    id: "110",
    title: "CENTRO MEDICO DRES. FUENTES Y ROMANO",
    name: "CENTRO MEDICO DRES. FUENTES Y ROMANO",
    city: "Distrito Nacional",
    citySelect: "Distrito Nacional",
    type: "Cl\u00ednica",
    typeSelect: "Cl\u00ednica",
    phone: "809.685.8286",
    phoneText: "809.685.8286",
  },
  {
    key: "113",
    id: "113",
    title: "CENTRO MEDICO EL VERGEL",
    name: "CENTRO MEDICO EL VERGEL",
    city: "Distrito Nacional",
    citySelect: "Distrito Nacional",
    type: "Cl\u00ednica",
    typeSelect: "Cl\u00ednica",
    phone: "809.732.1777",
    phoneText: "809.732.1777",
  },
  {
    key: "117",
    id: "117",
    title: "CENTRO MEDICO GINEC.OBST. & CIRUGIA DR. MARTINEZ",
    name: "CENTRO MEDICO GINEC.OBST. & CIRUGIA DR. MARTINEZ",
    city: "Distrito Nacional",
    citySelect: "Distrito Nacional",
    type: "Cl\u00ednica",
    typeSelect: "Cl\u00ednica",
    phone: "809.687.8425",
    phoneText: "809.687.8425",
  },
  {
    key: "127",
    id: "127",
    title: "CENTRO MEDICO LUPERON",
    name: "CENTRO MEDICO LUPERON",
    city: "Distrito Nacional",
    citySelect: "Distrito Nacional",
    type: "Cl\u00ednica",
    typeSelect: "Cl\u00ednica",
    phone: "809.684.3989",
    phoneText: "809.684.3989",
  },
  {
    key: "138",
    id: "138",
    title: "CENTRO MEDICO RICHARDSON CRUZ",
    name: "CENTRO MEDICO RICHARDSON CRUZ",
    city: "Distrito Nacional",
    citySelect: "Distrito Nacional",
    type: "Cl\u00ednica",
    typeSelect: "Cl\u00ednica",
    phone: "809.567.1471",
    phoneText: "809.567.1471",
  },
  {
    key: "146",
    id: "146",
    title: "CENTRO MEDICO VISTA DEL JARDIN",
    name: "CENTRO MEDICO VISTA DEL JARDIN",
    city: "Distrito Nacional",
    citySelect: "Distrito Nacional",
    type: "Cl\u00ednica",
    typeSelect: "Cl\u00ednica",
    phone: "809.563.9923",
    phoneText: "809.563.9923",
  },
  {
    key: "157",
    id: "157",
    title: "CLINICA CRUZ JIMINIAN, SRL",
    name: "CLINICA CRUZ JIMINIAN, SRL",
    city: "Distrito Nacional",
    citySelect: "Distrito Nacional",
    type: "Cl\u00ednica",
    typeSelect: "Cl\u00ednica",
    phone: "809.566.2271",
    phoneText: "809.566.2271",
  },
  {
    key: "160",
    id: "160",
    title: "CLINICA DR. ABEL GONZALEZ",
    name: "CLINICA DR. ABEL GONZALEZ",
    city: "Distrito Nacional",
    citySelect: "Distrito Nacional",
    type: "Cl\u00ednica",
    typeSelect: "Cl\u00ednica",
    phone: "809.682.6001",
    phoneText: "809.682.6001",
  },
  {
    key: "167",
    id: "167",
    title: "CLINICA DR. RODRIGUEZ SANTOS",
    name: "CLINICA DR. RODRIGUEZ SANTOS",
    city: "Distrito Nacional",
    citySelect: "Distrito Nacional",
    type: "Cl\u00ednica",
    typeSelect: "Cl\u00ednica",
    phone: "809.333.6671",
    phoneText: "809.333.6671",
  },
  {
    key: "175",
    id: "175",
    title: "CLINICA FUNDACION NUEVA ESPERANZA INC.",
    name: "CLINICA FUNDACION NUEVA ESPERANZA INC.",
    city: "Distrito Nacional",
    citySelect: "Distrito Nacional",
    type: "Cl\u00ednica",
    typeSelect: "Cl\u00ednica",
    phone: "809.681.2870",
    phoneText: "809.681.2870",
  },
  {
    key: "176",
    id: "176",
    title: "CLINICA GOMEZ PATI",
    name: "CLINICA GOMEZ PATI",
    city: "Distrito Nacional",
    citySelect: "Distrito Nacional",
    type: "Cl\u00ednica",
    typeSelect: "Cl\u00ednica",
    phone: "809.685.9131",
    phoneText: "809.685.9131",
  },
  {
    key: "179",
    id: "179",
    title: "CLINICA INDEPENDENCIA",
    name: "CLINICA INDEPENDENCIA",
    city: "Distrito Nacional",
    citySelect: "Distrito Nacional",
    type: "Cl\u00ednica",
    typeSelect: "Cl\u00ednica",
    phone: "809.533.2775",
    phoneText: "809.533.2775",
  },
  {
    key: "180",
    id: "180",
    title: "CLINICA INDEPENDENCIA NORTE",
    name: "CLINICA INDEPENDENCIA NORTE",
    city: "Distrito Nacional",
    citySelect: "Distrito Nacional",
    type: "Cl\u00ednica",
    typeSelect: "Cl\u00ednica",
    phone: "809.385.2787",
    phoneText: "809.385.2787",
  },
  {
    key: "193",
    id: "193",
    title: "COMERCIALIZADORA DIVERSA, SRL",
    name: "COMERCIALIZADORA DIVERSA, SRL",
    city: "Distrito Nacional",
    citySelect: "Distrito Nacional",
    type: "Cl\u00ednica",
    typeSelect: "Cl\u00ednica",
    phone: "809.535.6902",
    phoneText: "809.535.6902",
  },
  {
    key: "194",
    id: "194",
    title: "CONSULTORIA MEDICA TIERGAU, SRL",
    name: "CONSULTORIA MEDICA TIERGAU, SRL",
    city: "Distrito Nacional",
    citySelect: "Distrito Nacional",
    type: "Cl\u00ednica",
    typeSelect: "Cl\u00ednica",
    phone: "809.221.8583",
    phoneText: "809.221.8583",
  },
  {
    key: "201",
    id: "201",
    title: "CTRO DE TERAPIA FISICA Y REHABILITACION DRA. LICEL",
    name: "CTRO DE TERAPIA FISICA Y REHABILITACION DRA. LICEL",
    city: "Distrito Nacional",
    citySelect: "Distrito Nacional",
    type: "Cl\u00ednica",
    typeSelect: "Cl\u00ednica",
    phone: "809.482.3375",
    phoneText: "809.482.3375",
  },
  {
    key: "206",
    id: "206",
    title: "DENTAL SERVICES",
    name: "DENTAL SERVICES",
    city: "Distrito Nacional",
    citySelect: "Distrito Nacional",
    type: "Cl\u00ednica",
    typeSelect: "Cl\u00ednica",
    phone: "809.687.8640",
    phoneText: "809.687.8640",
  },
  {
    key: "208",
    id: "208",
    title: "DIAGNOSTICA, S.A.",
    name: "DIAGNOSTICA, S.A.",
    city: "Distrito Nacional",
    citySelect: "Distrito Nacional",
    type: "Cl\u00ednica",
    typeSelect: "Cl\u00ednica",
    phone: "809.688.5260",
    phoneText: "809.688.5260",
  },
  {
    key: "210",
    id: "210",
    title: "F. P. NEGOCIOS MEDICOS, SRL",
    name: "F. P. NEGOCIOS MEDICOS, SRL",
    city: "Distrito Nacional",
    citySelect: "Distrito Nacional",
    type: "Cl\u00ednica",
    typeSelect: "Cl\u00ednica",
    phone: "809.540.2680",
    phoneText: "809.540.2680",
  },
  {
    key: "215",
    id: "215",
    title: "FARMACIA ADA, SRL",
    name: "FARMACIA ADA, SRL",
    city: "Distrito Nacional",
    citySelect: "Distrito Nacional",
    type: "Farmacia",
    typeSelect: "Farmacia",
    phone: "809.684.1588",
    phoneText: "809.684.1588",
  },
  {
    key: "223",
    id: "223",
    title: "FARMACIA BAIK ",
    name: "FARMACIA BAIK ",
    city: "Distrito Nacional",
    citySelect: "Distrito Nacional",
    type: "",
    typeSelect: "",
    phone: "809.482.6620",
    phoneText: "809.482.6620",
  },
  {
    key: "232",
    id: "232",
    title: "FARMACIA BRISAS DEL ISABELA",
    name: "FARMACIA BRISAS DEL ISABELA",
    city: "Distrito Nacional",
    citySelect: "Distrito Nacional",
    type: "",
    typeSelect: "",
    phone: "809.616.1407",
    phoneText: "809.616.1407",
  },
  {
    key: "233",
    id: "233",
    title: "FARMACIA CARMINA",
    name: "FARMACIA CARMINA",
    city: "Distrito Nacional",
    citySelect: "Distrito Nacional",
    type: "",
    typeSelect: "",
    phone: "809.685.3191",
    phoneText: "809.685.3191",
  },
  {
    key: "234",
    id: "234",
    title: "FARMACIA CAROL ACROPOLYS",
    name: "FARMACIA CAROL ACROPOLYS",
    city: "Distrito Nacional",
    citySelect: "Distrito Nacional",
    type: "",
    typeSelect: "",
    phone: "809.567.1002",
    phoneText: "809.567.1002",
  },
  {
    key: "235",
    id: "235",
    title: "FARMACIA CAROL ANDALUCIA",
    name: "FARMACIA CAROL ANDALUCIA",
    city: "Distrito Nacional",
    citySelect: "Distrito Nacional",
    type: "",
    typeSelect: "",
    phone: "809.620.8465",
    phoneText: "809.620.8465",
  },
  {
    key: "236",
    id: "236",
    title: "FARMACIA CAROL ARROYO HONDO",
    name: "FARMACIA CAROL ARROYO HONDO",
    city: "Distrito Nacional",
    citySelect: "Distrito Nacional",
    type: "",
    typeSelect: "",
    phone: "809.378.0808",
    phoneText: "809.378.0808",
  },
  {
    key: "239",
    id: "239",
    title: "FARMACIA CAROL EL MILLON",
    name: "FARMACIA CAROL EL MILLON",
    city: "Distrito Nacional",
    citySelect: "Distrito Nacional",
    type: "",
    typeSelect: "",
    phone: "000.000.0000",
    phoneText: "000.000.0000",
  },
  {
    key: "241",
    id: "241",
    title: "FARMACIA CAROL GAZCUE",
    name: "FARMACIA CAROL GAZCUE",
    city: "Distrito Nacional",
    citySelect: "Distrito Nacional",
    type: "",
    typeSelect: "",
    phone: "809.689.6000",
    phoneText: "809.689.6000",
  },
  {
    key: "242",
    id: "242",
    title: "FARMACIA CAROL GOMEZ",
    name: "FARMACIA CAROL GOMEZ",
    city: "Distrito Nacional",
    citySelect: "Distrito Nacional",
    type: "",
    typeSelect: "",
    phone: "809.682.7080",
    phoneText: "809.682.7080",
  },
  {
    key: "245",
    id: "245",
    title: "FARMACIA CAROL JULIETA",
    name: "FARMACIA CAROL JULIETA",
    city: "Distrito Nacional",
    citySelect: "Distrito Nacional",
    type: "",
    typeSelect: "",
    phone: "809.472.4040",
    phoneText: "809.472.4040",
  },
  {
    key: "246",
    id: "246",
    title: "FARMACIA CAROL LOPE DE VEGA",
    name: "FARMACIA CAROL LOPE DE VEGA",
    city: "Distrito Nacional",
    citySelect: "Distrito Nacional",
    type: "",
    typeSelect: "",
    phone: "809.541.6767",
    phoneText: "809.541.6767",
  },
  {
    key: "247",
    id: "247",
    title: "FARMACIA CAROL MALECON CENTER",
    name: "FARMACIA CAROL MALECON CENTER",
    city: "Distrito Nacional",
    citySelect: "Distrito Nacional",
    type: "",
    typeSelect: "",
    phone: "809.682.7997",
    phoneText: "809.682.7997",
  },
  {
    key: "248",
    id: "248",
    title: "FARMACIA CAROL MELGEN",
    name: "FARMACIA CAROL MELGEN",
    city: "Distrito Nacional",
    citySelect: "Distrito Nacional",
    type: "",
    typeSelect: "",
    phone: "809.482.0000",
    phoneText: "809.482.0000",
  },
  {
    key: "249",
    id: "249",
    title: "FARMACIA CAROL NACO",
    name: "FARMACIA CAROL NACO",
    city: "Distrito Nacional",
    citySelect: "Distrito Nacional",
    type: "",
    typeSelect: "",
    phone: "809.562.6767",
    phoneText: "809.562.6767",
  },
  {
    key: "250",
    id: "250",
    title: "FARMACIA CAROL NOVO CENTRO",
    name: "FARMACIA CAROL NOVO CENTRO",
    city: "Distrito Nacional",
    citySelect: "Distrito Nacional",
    type: "",
    typeSelect: "",
    phone: "809.540.8969",
    phoneText: "809.540.8969",
  },
  {
    key: "251",
    id: "251",
    title: "FARMACIA CAROL P.H.U.",
    name: "FARMACIA CAROL P.H.U.",
    city: "Distrito Nacional",
    citySelect: "Distrito Nacional",
    type: "",
    typeSelect: "",
    phone: "809.685.3375",
    phoneText: "809.685.3375",
  },
  {
    key: "252",
    id: "252",
    title: "FARMACIA CAROL PALACIO PRESidENCIAL",
    name: "FARMACIA CAROL PALACIO PRESidENCIAL",
    city: "Distrito Nacional",
    citySelect: "Distrito Nacional",
    type: "",
    typeSelect: "",
    phone: "809.685.0274",
    phoneText: "809.685.0274",
  },
  {
    key: "256",
    id: "256",
    title: "FARMACIA CAROL SAN CARLOS",
    name: "FARMACIA CAROL SAN CARLOS",
    city: "Distrito Nacional",
    citySelect: "Distrito Nacional",
    type: "",
    typeSelect: "",
    phone: "809.685.8024",
    phoneText: "809.685.8024",
  },
  {
    key: "257",
    id: "257",
    title: "FARMACIA CAROL SARASOTA",
    name: "FARMACIA CAROL SARASOTA",
    city: "Distrito Nacional",
    citySelect: "Distrito Nacional",
    type: "",
    typeSelect: "",
    phone: "809.482.5440",
    phoneText: "809.482.5440",
  },
  {
    key: "267",
    id: "267",
    title: "FARMACIA DEL PARQUE, SRL",
    name: "FARMACIA DEL PARQUE, SRL",
    city: "Distrito Nacional",
    citySelect: "Distrito Nacional",
    type: "",
    typeSelect: "",
    phone: "809.227.7555",
    phoneText: "809.227.7555",
  },
  {
    key: "280",
    id: "280",
    title: "FARMACIA GRACE",
    name: "FARMACIA GRACE",
    city: "Distrito Nacional",
    citySelect: "Distrito Nacional",
    type: "",
    typeSelect: "",
    phone: "809.566.7056",
    phoneText: "809.566.7056",
  },
  {
    key: "282",
    id: "282",
    title: "FARMACIA GRECIA, SRL",
    name: "FARMACIA GRECIA, SRL",
    city: "Distrito Nacional",
    citySelect: "Distrito Nacional",
    type: "",
    typeSelect: "",
    phone: "809.684.6884",
    phoneText: "809.684.6884",
  },
  {
    key: "286",
    id: "286",
    title: "FARMACIA KARINES",
    name: "FARMACIA KARINES",
    city: "Distrito Nacional",
    citySelect: "Distrito Nacional",
    type: "",
    typeSelect: "",
    phone: "809.533.5003",
    phoneText: "809.533.5003",
  },
  {
    key: "292",
    id: "292",
    title: "FARMACIA MACORIX, S.A.",
    name: "FARMACIA MACORIX, S.A.",
    city: "Distrito Nacional",
    citySelect: "Distrito Nacional",
    type: "Farmacia",
    typeSelect: "Farmacia",
    phone: "809.532.1226",
    phoneText: "809.532.1226",
  },
  {
    key: "296",
    id: "296",
    title: "FARMACIA METROPOLIS, SRL",
    name: "FARMACIA METROPOLIS, SRL",
    city: "Distrito Nacional",
    citySelect: "Distrito Nacional",
    type: "",
    typeSelect: "",
    phone: "809.682.1150",
    phoneText: "809.682.1150",
  },
  {
    key: "297",
    id: "297",
    title: "FARMACIA MIGUELINA, SRL",
    name: "FARMACIA MIGUELINA, SRL",
    city: "Distrito Nacional",
    citySelect: "Distrito Nacional",
    type: "",
    typeSelect: "",
    phone: "809.684.6039",
    phoneText: "809.684.6039",
  },
  {
    key: "298",
    id: "298",
    title: "FARMACIA MILAGROS DE LA CARidAD",
    name: "FARMACIA MILAGROS DE LA CARidAD",
    city: "Distrito Nacional",
    citySelect: "Distrito Nacional",
    type: "",
    typeSelect: "",
    phone: "809.689.7742",
    phoneText: "809.689.7742",
  },
  {
    key: "318",
    id: "318",
    title: "FARMACIA SAN JUDAS TADEO",
    name: "FARMACIA SAN JUDAS TADEO",
    city: "Distrito Nacional",
    citySelect: "Distrito Nacional",
    type: "",
    typeSelect: "",
    phone: "809.685.8165",
    phoneText: "809.685.8165",
  },
  {
    key: "322",
    id: "322",
    title: "FARMACIA SANTJESS",
    name: "FARMACIA SANTJESS",
    city: "Distrito Nacional",
    citySelect: "Distrito Nacional",
    type: "",
    typeSelect: "",
    phone: "809.262.0630",
    phoneText: "809.262.0630",
  },
  {
    key: "329",
    id: "329",
    title: "FARMACONAL",
    name: "FARMACONAL",
    city: "Distrito Nacional",
    citySelect: "Distrito Nacional",
    type: "",
    typeSelect: "",
    phone: "809.381.0906",
    phoneText: "809.381.0906",
  },
  {
    key: "331",
    id: "331",
    title: "FARMAX ARROYO HONDO",
    name: "FARMAX ARROYO HONDO",
    city: "Distrito Nacional",
    citySelect: "Distrito Nacional",
    type: "",
    typeSelect: "",
    phone: "809.338.7070",
    phoneText: "809.338.7070",
  },
  {
    key: "332",
    id: "332",
    title: "FARMAX CAMINO CHIQUITO",
    name: "FARMAX CAMINO CHIQUITO",
    city: "Distrito Nacional",
    citySelect: "Distrito Nacional",
    type: "",
    typeSelect: "",
    phone: "809.333.4444",
    phoneText: "809.333.4444",
  },
  {
    key: "333",
    id: "333",
    title: "FARMAX CHARLES SUMMER",
    name: "FARMAX CHARLES SUMMER",
    city: "Distrito Nacional",
    citySelect: "Distrito Nacional",
    type: "",
    typeSelect: "",
    phone: "809.333.4444",
    phoneText: "809.333.4444",
  },
  {
    key: "334",
    id: "334",
    title: "FARMAX GAZCUE",
    name: "FARMAX GAZCUE",
    city: "Distrito Nacional",
    citySelect: "Distrito Nacional",
    type: "",
    typeSelect: "",
    phone: "809.333.4444",
    phoneText: "809.333.4444",
  },
  {
    key: "335",
    id: "335",
    title: "FARMAX JUMBO LUPERON",
    name: "FARMAX JUMBO LUPERON",
    city: "Distrito Nacional",
    citySelect: "Distrito Nacional",
    type: "",
    typeSelect: "",
    phone: "809.333.4444",
    phoneText: "809.333.4444",
  },
  {
    key: "340",
    id: "340",
    title: "FARMAX LA SIRENA CHURCHILL",
    name: "FARMAX LA SIRENA CHURCHILL",
    city: "Distrito Nacional",
    citySelect: "Distrito Nacional",
    type: "",
    typeSelect: "",
    phone: "809.333.4444",
    phoneText: "809.333.4444",
  },
  {
    key: "343",
    id: "343",
    title: "FARMAX LOPE DE VEGA",
    name: "FARMAX LOPE DE VEGA",
    city: "Distrito Nacional",
    citySelect: "Distrito Nacional",
    type: "",
    typeSelect: "",
    phone: "809.333.4444",
    phoneText: "809.333.4444",
  },
  {
    key: "346",
    id: "346",
    title: "FARMAX NACIONAL 27 DE FEBRERO",
    name: "FARMAX NACIONAL 27 DE FEBRERO",
    city: "Distrito Nacional",
    citySelect: "Distrito Nacional",
    type: "",
    typeSelect: "",
    phone: "809.333.4444",
    phoneText: "809.333.4444",
  },
  {
    key: "348",
    id: "348",
    title: "FARMAX NACIONAL LOPE DE VEGA",
    name: "FARMAX NACIONAL LOPE DE VEGA",
    city: "Distrito Nacional",
    citySelect: "Distrito Nacional",
    type: "",
    typeSelect: "",
    phone: "809.333.4444",
    phoneText: "809.333.4444",
  },
  {
    key: "349",
    id: "349",
    title: "FARMAX NU",
    name: "FARMAX NU",
    city: "Distrito Nacional",
    citySelect: "Distrito Nacional",
    type: "",
    typeSelect: "",
    phone: "809.333.4444",
    phoneText: "809.333.4444",
  },
  {
    key: "353",
    id: "353",
    title: "FARMAX SARASOTA",
    name: "FARMAX SARASOTA",
    city: "Distrito Nacional",
    citySelect: "Distrito Nacional",
    type: "",
    typeSelect: "",
    phone: "809.333.4444",
    phoneText: "809.333.4444",
  },
  {
    key: "354",
    id: "354",
    title: "FARMAX SUPERPOLA LOPE DE VEGA",
    name: "FARMAX SUPERPOLA LOPE DE VEGA",
    city: "Distrito Nacional",
    citySelect: "Distrito Nacional",
    type: "",
    typeSelect: "",
    phone: "809.333.4444",
    phoneText: "809.333.4444",
  },
  {
    key: "355",
    id: "355",
    title: "FARMAX SUPERPOLA SARASOTA",
    name: "FARMAX SUPERPOLA SARASOTA",
    city: "Distrito Nacional",
    citySelect: "Distrito Nacional",
    type: "",
    typeSelect: "",
    phone: "809.333.4444",
    phoneText: "809.333.4444",
  },
  {
    key: "358",
    id: "358",
    title: "FUNDACION ACTIVO 20.30, INC.",
    name: "FUNDACION ACTIVO 20.30, INC.",
    city: "Distrito Nacional",
    citySelect: "Distrito Nacional",
    type: "Cl\u00ednica",
    typeSelect: "Cl\u00ednica",
    phone: "809.684.0082",
    phoneText: "809.684.0082",
  },
  {
    key: "359",
    id: "359",
    title: "GLOBAL MEDICA DOMINICANA, SRL",
    name: "GLOBAL MEDICA DOMINICANA, SRL",
    city: "Distrito Nacional",
    citySelect: "Distrito Nacional",
    type: "Cl\u00ednica",
    typeSelect: "Cl\u00ednica",
    phone: "809.333.1100",
    phoneText: "809.333.1100",
  },
  {
    key: "360",
    id: "360",
    title: "GRUPO CAROL, S.A.",
    name: "GRUPO CAROL, S.A.",
    city: "Distrito Nacional",
    citySelect: "Distrito Nacional",
    type: "Cl\u00ednica",
    typeSelect: "Cl\u00ednica",
    phone: "809.563.6060",
    phoneText: "809.563.6060",
  },
  {
    key: "372",
    id: "372",
    title: "GRUPO MEDICO SAN MARTIN",
    name: "GRUPO MEDICO SAN MARTIN",
    city: "Distrito Nacional",
    citySelect: "Distrito Nacional",
    type: "Cl\u00ednica",
    typeSelect: "Cl\u00ednica",
    phone: "809.565.1777",
    phoneText: "809.565.1777",
  },
  {
    key: "374",
    id: "374",
    title: "HOSPAL MEDICA",
    name: "HOSPAL MEDICA",
    city: "Distrito Nacional",
    citySelect: "Distrito Nacional",
    type: "Cl\u00ednica",
    typeSelect: "Cl\u00ednica",
    phone: "809.683.0014",
    phoneText: "809.683.0014",
  },
  {
    key: "380",
    id: "380",
    title: "HOSPITAL GENERAL PLAZA DE LA SALUD",
    name: "HOSPITAL GENERAL PLAZA DE LA SALUD",
    city: "Distrito Nacional",
    citySelect: "Distrito Nacional",
    type: "Cl\u00ednica",
    typeSelect: "Cl\u00ednica",
    phone: "809.565.7477",
    phoneText: "809.565.7477",
  },
  {
    key: "396",
    id: "396",
    title: "INSTITUTO DE CIENCIA VISUALES DE LAS AMERICAS",
    name: "INSTITUTO DE CIENCIA VISUALES DE LAS AMERICAS",
    city: "Distrito Nacional",
    citySelect: "Distrito Nacional",
    type: "Cl\u00ednica",
    typeSelect: "Cl\u00ednica",
    phone: "809.565.3192",
    phoneText: "809.565.3192",
  },
  {
    key: "398",
    id: "398",
    title: "INSTITUTO DE MEDICINA POPULAR (MODERNO)",
    name: "INSTITUTO DE MEDICINA POPULAR (MODERNO)",
    city: "Distrito Nacional",
    citySelect: "Distrito Nacional",
    type: "Cl\u00ednica",
    typeSelect: "Cl\u00ednica",
    phone: "809.548.3131",
    phoneText: "809.548.3131",
  },
  {
    key: "400",
    id: "400",
    title: "INTEGRAMEDICA",
    name: "INTEGRAMEDICA",
    city: "Distrito Nacional",
    citySelect: "Distrito Nacional",
    type: "Cl\u00ednica",
    typeSelect: "Cl\u00ednica",
    phone: "809.685.0022",
    phoneText: "809.685.0022",
  },
  {
    key: "401",
    id: "401",
    title: "INVERSIONES TORRES SERRATA (FARMACIA BAIK)",
    name: "INVERSIONES TORRES SERRATA (FARMACIA BAIK)",
    city: "Distrito Nacional",
    citySelect: "Distrito Nacional",
    type: "Cl\u00ednica",
    typeSelect: "Cl\u00ednica",
    phone: "809.535.4626",
    phoneText: "809.535.4626",
  },
  {
    key: "402",
    id: "402",
    title: "ISORFFIX, SRL",
    name: "ISORFFIX, SRL",
    city: "Distrito Nacional",
    citySelect: "Distrito Nacional",
    type: "Cl\u00ednica",
    typeSelect: "Cl\u00ednica",
    phone: "809.620.2880",
    phoneText: "809.620.2880",
  },
  {
    key: "403",
    id: "403",
    title: "KHERSUN, S.A.",
    name: "KHERSUN, S.A.",
    city: "Distrito Nacional",
    citySelect: "Distrito Nacional",
    type: "Cl\u00ednica",
    typeSelect: "Cl\u00ednica",
    phone: "809.567.1200",
    phoneText: "809.567.1200",
  },
  {
    key: "405",
    id: "405",
    title: "LAB. CLINICO CORTINA GONZALEZ . EL VERGEL",
    name: "LAB. CLINICO CORTINA GONZALEZ . EL VERGEL",
    city: "Distrito Nacional",
    citySelect: "Distrito Nacional",
    type: "Laboratorio",
    typeSelect: "Laboratorio",
    phone: "809.338.0058",
    phoneText: "809.338.0058",
  },
  {
    key: "408",
    id: "408",
    title: "LAB. DE PAT. DRES. DIAZ GONZALEZ & DIAZ MARTINEZ",
    name: "LAB. DE PAT. DRES. DIAZ GONZALEZ & DIAZ MARTINEZ",
    city: "Distrito Nacional",
    citySelect: "Distrito Nacional",
    type: "Laboratorio",
    typeSelect: "Laboratorio",
    phone: "000.000.0000",
    phoneText: "000.000.0000",
  },
  {
    key: "409",
    id: "409",
    title: "LABORATORIO AMADITA",
    name: "LABORATORIO AMADITA",
    city: "Distrito Nacional",
    citySelect: "Distrito Nacional",
    type: "Laboratorio",
    typeSelect: "Laboratorio",
    phone: "809.682.5414",
    phoneText: "809.682.5414",
  },
  {
    key: "412",
    id: "412",
    title: "LABORATORIO CLINICO ASOCIADO",
    name: "LABORATORIO CLINICO ASOCIADO",
    city: "Distrito Nacional",
    citySelect: "Distrito Nacional",
    type: "Laboratorio",
    typeSelect: "Laboratorio",
    phone: "809.688.5086",
    phoneText: "809.688.5086",
  },
  {
    key: "413",
    id: "413",
    title: "LABORATORIO CLINICO CORTINA GONZALEZ",
    name: "LABORATORIO CLINICO CORTINA GONZALEZ",
    city: "Distrito Nacional",
    citySelect: "Distrito Nacional",
    type: "Laboratorio",
    typeSelect: "Laboratorio",
    phone: "809.221.4224",
    phoneText: "809.221.4224",
  },
  {
    key: "427",
    id: "427",
    title: "LABORATORIO DE PATOLOGIA DR. BALTAZAR PIMENTEL",
    name: "LABORATORIO DE PATOLOGIA DR. BALTAZAR PIMENTEL",
    city: "Distrito Nacional",
    citySelect: "Distrito Nacional",
    type: "Laboratorio",
    typeSelect: "Laboratorio",
    phone: "809.732.0995",
    phoneText: "809.732.0995",
  },
  {
    key: "428",
    id: "428",
    title: "LABORATORIO DE REFERENCIAS",
    name: "LABORATORIO DE REFERENCIAS",
    city: "Distrito Nacional",
    citySelect: "Distrito Nacional",
    type: "Laboratorio",
    typeSelect: "Laboratorio",
    phone: "809.221.5545",
    phoneText: "809.221.5545",
  },
  {
    key: "429",
    id: "429",
    title: "LABORATORIO DR. KOURIE, SRL",
    name: "LABORATORIO DR. KOURIE, SRL",
    city: "Distrito Nacional",
    citySelect: "Distrito Nacional",
    type: "Laboratorio",
    typeSelect: "Laboratorio",
    phone: "809.532.3370",
    phoneText: "809.532.3370",
  },
  {
    key: "432",
    id: "432",
    title: "LAUDIO AUDIOLOGIA",
    name: "LAUDIO AUDIOLOGIA",
    city: "Distrito Nacional",
    citySelect: "Distrito Nacional",
    type: "Cl\u00ednica",
    typeSelect: "Cl\u00ednica",
    phone: "809.687.8306",
    phoneText: "809.687.8306",
  },
  {
    key: "433",
    id: "433",
    title: "LIGA DOMINICANA CONTRA EL CANCER, INC.",
    name: "LIGA DOMINICANA CONTRA EL CANCER, INC.",
    city: "Distrito Nacional",
    citySelect: "Distrito Nacional",
    type: "Cl\u00ednica",
    typeSelect: "Cl\u00ednica",
    phone: "809.221.4002",
    phoneText: "809.221.4002",
  },
  {
    key: "436",
    id: "436",
    title: "MEDICINA NUCLEAR",
    name: "MEDICINA NUCLEAR",
    city: "Distrito Nacional",
    citySelect: "Distrito Nacional",
    type: "Cl\u00ednica",
    typeSelect: "Cl\u00ednica",
    phone: "809.221.4852",
    phoneText: "809.221.4852",
  },
  {
    key: "438",
    id: "438",
    title: "MEDidENTAL, SRL",
    name: "MEDidENTAL, SRL",
    city: "Distrito Nacional",
    citySelect: "Distrito Nacional",
    type: "Cl\u00ednica",
    typeSelect: "Cl\u00ednica",
    phone: "809.686.2688",
    phoneText: "809.686.2688",
  },
  {
    key: "439",
    id: "439",
    title: "MEDIIMPLANTES, SRL",
    name: "MEDIIMPLANTES, SRL",
    city: "Distrito Nacional",
    citySelect: "Distrito Nacional",
    type: "Cl\u00ednica",
    typeSelect: "Cl\u00ednica",
    phone: "809.688.1616",
    phoneText: "809.688.1616",
  },
  {
    key: "442",
    id: "442",
    title: "MULTIMAGEN DIAGNOSTICA",
    name: "MULTIMAGEN DIAGNOSTICA",
    city: "Distrito Nacional",
    citySelect: "Distrito Nacional",
    type: "Cl\u00ednica",
    typeSelect: "Cl\u00ednica",
    phone: "809.338.0415",
    phoneText: "809.338.0415",
  },
  {
    key: "443",
    id: "443",
    title: "MULTISERVICIOS CALDEA SRL ( FCIA BAIK II )",
    name: "MULTISERVICIOS CALDEA SRL ( FCIA BAIK II )",
    city: "Distrito Nacional",
    citySelect: "Distrito Nacional",
    type: "Cl\u00ednica",
    typeSelect: "Cl\u00ednica",
    phone: "809.533.8802",
    phoneText: "809.533.8802",
  },
  {
    key: "444",
    id: "444",
    title: "NEFRODOM, SRL",
    name: "NEFRODOM, SRL",
    city: "Distrito Nacional",
    citySelect: "Distrito Nacional",
    type: "Cl\u00ednica",
    typeSelect: "Cl\u00ednica",
    phone: "809.689.7701",
    phoneText: "809.689.7701",
  },
  {
    key: "445",
    id: "445",
    title: "NEGOCIOS MAR DE CORAL, SRL",
    name: "NEGOCIOS MAR DE CORAL, SRL",
    city: "Distrito Nacional",
    citySelect: "Distrito Nacional",
    type: "Cl\u00ednica",
    typeSelect: "Cl\u00ednica",
    phone: "809.687.0322",
    phoneText: "809.687.0322",
  },
  {
    key: "446",
    id: "446",
    title: "NEPHRON DIALISIS, C. POR A.",
    name: "NEPHRON DIALISIS, C. POR A.",
    city: "Distrito Nacional",
    citySelect: "Distrito Nacional",
    type: "Cl\u00ednica",
    typeSelect: "Cl\u00ednica",
    phone: "809.338.9982",
    phoneText: "809.338.9982",
  },
  {
    key: "447",
    id: "447",
    title: "ODONTOLOGIA DOMINICANA, SRL",
    name: "ODONTOLOGIA DOMINICANA, SRL",
    city: "Distrito Nacional",
    citySelect: "Distrito Nacional",
    type: "Cl\u00ednica",
    typeSelect: "Cl\u00ednica",
    phone: "809.541.2840",
    phoneText: "809.541.2840",
  },
  {
    key: "448",
    id: "448",
    title: "OFTALMOLOGIA ESPECIALIZADA",
    name: "OFTALMOLOGIA ESPECIALIZADA",
    city: "Distrito Nacional",
    citySelect: "Distrito Nacional",
    type: "Cl\u00ednica",
    typeSelect: "Cl\u00ednica",
    phone: "809.616.1810",
    phoneText: "809.616.1810",
  },
  {
    key: "449",
    id: "449",
    title: "ONCOSERV SANTO DOMINGO",
    name: "ONCOSERV SANTO DOMINGO",
    city: "Distrito Nacional",
    citySelect: "Distrito Nacional",
    type: "Cl\u00ednica",
    typeSelect: "Cl\u00ednica",
    phone: "(829).547.78",
    phoneText: "(829).547.78",
  },
  {
    key: "450",
    id: "450",
    title: "ORTHOPHARMA EXPRESS",
    name: "ORTHOPHARMA EXPRESS",
    city: "Distrito Nacional",
    citySelect: "Distrito Nacional",
    type: "Cl\u00ednica",
    typeSelect: "Cl\u00ednica",
    phone: "809.534.5854",
    phoneText: "809.534.5854",
  },
  {
    key: "451",
    id: "451",
    title: "ORTOTECNICA",
    name: "ORTOTECNICA",
    city: "Distrito Nacional",
    citySelect: "Distrito Nacional",
    type: "Cl\u00ednica",
    typeSelect: "Cl\u00ednica",
    phone: "809.616.2268",
    phoneText: "809.616.2268",
  },
  {
    key: "452",
    id: "452",
    title: "PERFECT VISION G Y R, SRL",
    name: "PERFECT VISION G Y R, SRL",
    city: "Distrito Nacional",
    citySelect: "Distrito Nacional",
    type: "Cl\u00ednica",
    typeSelect: "Cl\u00ednica",
    phone: "809.732.9988",
    phoneText: "809.732.9988",
  },
  {
    key: "453",
    id: "453",
    title: "PHARMATECH",
    name: "PHARMATECH",
    city: "Distrito Nacional",
    citySelect: "Distrito Nacional",
    type: "Cl\u00ednica",
    typeSelect: "Cl\u00ednica",
    phone: "809.620.8000",
    phoneText: "809.620.8000",
  },
  {
    key: "455",
    id: "455",
    title: "PROCEDIMIENTOS Y DIAGNOSTICOS ESPECIALES, S.A.",
    name: "PROCEDIMIENTOS Y DIAGNOSTICOS ESPECIALES, S.A.",
    city: "Distrito Nacional",
    citySelect: "Distrito Nacional",
    type: "Cl\u00ednica",
    typeSelect: "Cl\u00ednica",
    phone: "809.685.9131",
    phoneText: "809.685.9131",
  },
  {
    key: "456",
    id: "456",
    title: "PROMED",
    name: "PROMED",
    city: "Distrito Nacional",
    citySelect: "Distrito Nacional",
    type: "Cl\u00ednica",
    typeSelect: "Cl\u00ednica",
    phone: "809.948.8400",
    phoneText: "809.948.8400",
  },
  {
    key: "457",
    id: "457",
    title: "PRONTO MEDICAL DOMINICANA, S.A.",
    name: "PRONTO MEDICAL DOMINICANA, S.A.",
    city: "Distrito Nacional",
    citySelect: "Distrito Nacional",
    type: "Cl\u00ednica",
    typeSelect: "Cl\u00ednica",
    phone: "809.685.7140",
    phoneText: "809.685.7140",
  },
  {
    key: "459",
    id: "459",
    title: "PUNTO MEDICO FAMILIAR CIUDAD UNIVERSITARIA",
    name: "PUNTO MEDICO FAMILIAR CIUDAD UNIVERSITARIA",
    city: "Distrito Nacional",
    citySelect: "Distrito Nacional",
    type: "Cl\u00ednica",
    typeSelect: "Cl\u00ednica",
    phone: "809.535.2700",
    phoneText: "809.535.2700",
  },
  {
    key: "460",
    id: "460",
    title: "PUNTO MEDICO FAMILIAR LUPERON",
    name: "PUNTO MEDICO FAMILIAR LUPERON",
    city: "Distrito Nacional",
    citySelect: "Distrito Nacional",
    type: "Cl\u00ednica",
    typeSelect: "Cl\u00ednica",
    phone: "809.740.0181",
    phoneText: "809.740.0181",
  },
  {
    key: "463",
    id: "463",
    title: "RAMBLA ENTERPRISE, SRL",
    name: "RAMBLA ENTERPRISE, SRL",
    city: "Distrito Nacional",
    citySelect: "Distrito Nacional",
    type: "Cl\u00ednica",
    typeSelect: "Cl\u00ednica",
    phone: "809.544.0047",
    phoneText: "809.544.0047",
  },
  {
    key: "464",
    id: "464",
    title: "RAVILLA S.A, FARMA XPRESS",
    name: "RAVILLA S.A, FARMA XPRESS",
    city: "Distrito Nacional",
    citySelect: "Distrito Nacional",
    type: "",
    typeSelect: "",
    phone: "809.385.1000",
    phoneText: "809.385.1000",
  },
  {
    key: "465",
    id: "465",
    title: "RAVILLA S.A. (FARMAXPRESS)",
    name: "RAVILLA S.A. (FARMAXPRESS)",
    city: "Distrito Nacional",
    citySelect: "Distrito Nacional",
    type: "",
    typeSelect: "",
    phone: "809.682.7979",
    phoneText: "809.682.7979",
  },
  {
    key: "466",
    id: "466",
    title: "RAVILLA S.A. (FARMAXPRESS)",
    name: "RAVILLA S.A. (FARMAXPRESS)",
    city: "Distrito Nacional",
    citySelect: "Distrito Nacional",
    type: "",
    typeSelect: "",
    phone: "809.227.6616",
    phoneText: "809.227.6616",
  },
  {
    key: "467",
    id: "467",
    title: "RAVILLA, S.A FARMA XPRESS . LAMA CHURCHILL",
    name: "RAVILLA, S.A FARMA XPRESS . LAMA CHURCHILL",
    city: "Distrito Nacional",
    citySelect: "Distrito Nacional",
    type: "",
    typeSelect: "",
    phone: "809.286.0050",
    phoneText: "809.286.0050",
  },
  {
    key: "468",
    id: "468",
    title: "RAVILLA, S.A FARMA XPRESS . LAMA DUARTE",
    name: "RAVILLA, S.A FARMA XPRESS . LAMA DUARTE",
    city: "Distrito Nacional",
    citySelect: "Distrito Nacional",
    type: "",
    typeSelect: "",
    phone: "809.685.0030",
    phoneText: "809.685.0030",
  },
  {
    key: "470",
    id: "470",
    title: "REFERENCIA CENTRO ARROYO HONDO",
    name: "REFERENCIA CENTRO ARROYO HONDO",
    city: "Distrito Nacional",
    citySelect: "Distrito Nacional",
    type: "Laboratorio",
    typeSelect: "Laboratorio",
    phone: "809.221.5545",
    phoneText: "809.221.5545",
  },
  {
    key: "471",
    id: "471",
    title: "REFERENCIA CENTRO CACIQUE",
    name: "REFERENCIA CENTRO CACIQUE",
    city: "Distrito Nacional",
    citySelect: "Distrito Nacional",
    type: "Laboratorio",
    typeSelect: "Laboratorio",
    phone: "809.221.5545",
    phoneText: "809.221.5545",
  },
  {
    key: "473",
    id: "473",
    title: "REFERENCIA CENTRO DON BOSCO",
    name: "REFERENCIA CENTRO DON BOSCO",
    city: "Distrito Nacional",
    citySelect: "Distrito Nacional",
    type: "Laboratorio",
    typeSelect: "Laboratorio",
    phone: "809.412.7204",
    phoneText: "809.412.7204",
  },
  {
    key: "474",
    id: "474",
    title: "REFERENCIA CENTRO GAZCUE (UCE)",
    name: "REFERENCIA CENTRO GAZCUE (UCE)",
    city: "Distrito Nacional",
    citySelect: "Distrito Nacional",
    type: "Laboratorio",
    typeSelect: "Laboratorio",
    phone: "809.221.5545",
    phoneText: "809.221.5545",
  },
  {
    key: "478",
    id: "478",
    title: "REFERENCIA CENTRO JULIETA",
    name: "REFERENCIA CENTRO JULIETA",
    city: "Distrito Nacional",
    citySelect: "Distrito Nacional",
    type: "Laboratorio",
    typeSelect: "Laboratorio",
    phone: "809.221.5545",
    phoneText: "809.221.5545",
  },
  {
    key: "480",
    id: "480",
    title: "REFERENCIA CENTRO MILLON",
    name: "REFERENCIA CENTRO MILLON",
    city: "Distrito Nacional",
    citySelect: "Distrito Nacional",
    type: "Laboratorio",
    typeSelect: "Laboratorio",
    phone: "809.221.5545",
    phoneText: "809.221.5545",
  },
  {
    key: "481",
    id: "481",
    title: "REFERENCIA CENTRO NACO",
    name: "REFERENCIA CENTRO NACO",
    city: "Distrito Nacional",
    citySelect: "Distrito Nacional",
    type: "Laboratorio",
    typeSelect: "Laboratorio",
    phone: "809.221.5545",
    phoneText: "809.221.5545",
  },
  {
    key: "483",
    id: "483",
    title: "REFERENCIA CENTRO PIANTINI",
    name: "REFERENCIA CENTRO PIANTINI",
    city: "Distrito Nacional",
    citySelect: "Distrito Nacional",
    type: "Laboratorio",
    typeSelect: "Laboratorio",
    phone: "809.221.5545",
    phoneText: "809.221.5545",
  },
  {
    key: "485",
    id: "485",
    title: "REFERENCIA CENTRO SARASOTA",
    name: "REFERENCIA CENTRO SARASOTA",
    city: "Distrito Nacional",
    citySelect: "Distrito Nacional",
    type: "Laboratorio",
    typeSelect: "Laboratorio",
    phone: "809.221.5545",
    phoneText: "809.221.5545",
  },
  {
    key: "487",
    id: "487",
    title: "SALUD EN RED NACIONAL (SERENA)",
    name: "SALUD EN RED NACIONAL (SERENA)",
    city: "Distrito Nacional",
    citySelect: "Distrito Nacional",
    type: "Laboratorio",
    typeSelect: "Laboratorio",
    phone: "809.688.6232",
    phoneText: "809.688.6232",
  },
  {
    key: "488",
    id: "488",
    title: "SER SALUD",
    name: "SER SALUD",
    city: "Distrito Nacional",
    citySelect: "Distrito Nacional",
    type: "Cl\u00ednica",
    typeSelect: "Cl\u00ednica",
    phone: "809.539.7525",
    phoneText: "809.539.7525",
  },
  {
    key: "496",
    id: "496",
    title: "SURGICAL SOLUTIONS INTERNACIONAL, SRL",
    name: "SURGICAL SOLUTIONS INTERNACIONAL, SRL",
    city: "Distrito Nacional",
    citySelect: "Distrito Nacional",
    type: "Cl\u00ednica",
    typeSelect: "Cl\u00ednica",
    phone: "809.653.3343",
    phoneText: "809.653.3343",
  },
  {
    key: "497",
    id: "497",
    title: "TECHNI.PRO CENTRO DE HEMODIALISIS",
    name: "TECHNI.PRO CENTRO DE HEMODIALISIS",
    city: "Distrito Nacional",
    citySelect: "Distrito Nacional",
    type: "Cl\u00ednica",
    typeSelect: "Cl\u00ednica",
    phone: "809.475.6518",
    phoneText: "809.475.6518",
  },
  {
    key: "502",
    id: "502",
    title: "UNIDAD DE HEMODIALISIS EL BUEN SAMARITANO",
    name: "UNIDAD DE HEMODIALISIS EL BUEN SAMARITANO",
    city: "Distrito Nacional",
    citySelect: "Distrito Nacional",
    type: "Cl\u00ednica",
    typeSelect: "Cl\u00ednica",
    phone: "809.333.6671",
    phoneText: "809.333.6671",
  },
  {
    key: "504",
    id: "504",
    title: "UNIDAD DE QUEMADO PEARLF.ORT",
    name: "UNIDAD DE QUEMADO PEARLF.ORT",
    city: "Distrito Nacional",
    citySelect: "Distrito Nacional",
    type: "Cl\u00ednica",
    typeSelect: "Cl\u00ednica",
    phone: "809.681.2750",
    phoneText: "809.681.2750",
  },
  {
    key: "505",
    id: "505",
    title: "UNIDAD DE TERAPIA FISICA Y REHAB. DR. FIGUEROA",
    name: "UNIDAD DE TERAPIA FISICA Y REHAB. DR. FIGUEROA",
    city: "Distrito Nacional",
    citySelect: "Distrito Nacional",
    type: "Cl\u00ednica",
    typeSelect: "Cl\u00ednica",
    phone: "809.687.1561",
    phoneText: "809.687.1561",
  },
];
